// cityDatabase.ts
export const cities = [
    "Tokyo, Japan",
    "Delhi, India",
    "Shanghai, China",
    "São Paulo, Brazil",
    "Mexico City, Mexico",
    "Cairo, Egypt",
    "Mumbai, India",
    "Beijing, China",
    "Dhaka, Bangladesh",
    "Osaka, Japan",
    "New York City, USA",
    "Karachi, Pakistan",
    "Buenos Aires, Argentina",
    "Chongqing, China",
    "Istanbul, Turkey",
    "Kolkata, India",
    "Manila, Philippines",
    "Lagos, Nigeria",
    "Rio de Janeiro, Brazil",
    "Tianjin, China",
    "Kinshasa, DR Congo",
    "Guangzhou, China",
    "Los Angeles, USA",
    "Moscow, Russia",
    "Shenzhen, China",
    "Lahore, Pakistan",
    "Bangalore, India",
    "Paris, France",
    "Bogotá, Colombia",
    "Jakarta, Indonesia",
    "Chennai, India",
    "Lima, Peru",
    "Bangkok, Thailand",
    "Seoul, South Korea",
    "London, UK",
    "Hyderabad, India",
    "Madrid, Spain",
    "Chicago, USA",
    "Rome, Italy",
    "Berlin, Germany",
    "Toronto, Canada",
    "Singapore",
    "Dubai, UAE",
    "Sydney, Australia",
    "Melbourne, Australia",
    "Amsterdam, Netherlands",
    "Barcelona, Spain",
    "Montreal, Canada",
    "Munich, Germany",
    "Stockholm, Sweden",
    "Athens, Greece",
    "Vienna, Austria",
    "Brussels, Belgium",
    "Dublin, Ireland",
    "Oslo, Norway",
    "Helsinki, Finland",
    "Copenhagen, Denmark",
    "Prague, Czech Republic",
    "Warsaw, Poland",
    "Budapest, Hungary",
    "Lisbon, Portugal",
    "Mumbai, India",
    "Vancouver, Canada",
    "San Francisco, USA",
    "Boston, USA",
    "Seattle, USA",
    "Miami, USA",
    "Las Vegas, USA",
    "Houston, USA",
    "Atlanta, USA",
    "Washington DC, USA",
    "Dallas, USA",
    "Phoenix, USA",
    "Philadelphia, USA",
    "Honolulu, USA",
    "Denver, USA",
    "Portland, USA",
    "Austin, USA",
    "Nashville, USA",
    "New Orleans, USA",
    "Sydney, Australia",
    "Auckland, New Zealand",
    "Wellington, New Zealand",
    "Brisbane, Australia",
    "Perth, Australia",
    "Adelaide, Australia",
    "Gold Coast, Australia",
    "Tehran, Iran",
    "Christchurch, New Zealand",
    // Add more cities as needed
];

// Helper function to search cities
export const searchCities = (query: string) => {
    const searchTerm = query.toLowerCase().trim();
    return searchTerm === '' 
        ? [] 
        : cities
            .filter(city => city.toLowerCase().includes(searchTerm))
            .slice(0, 8); // Limit to 8 suggestions
};